### ISSUE TITLE
I'm Getting Access Tokens

### ISSUE THREAD

**Issue by spottedmahn** [Gimly/NetCoreAngularAzureB2CMsal#4]
After the push from #1 I've been able to successfully get access tokens.  I haven't go the WebApi side working yet though.

![image](https://user-images.githubusercontent.com/14079228/31821925-c594da80-b574-11e7-9991-a456b6b8cc76.png)

**Comment by Gimly** [comment]
Wow good news! Now, why the hell doesn't it work for me 😡? Did you change something in the code? I guess you're trying with your own AD B2C tenant, is that right?

For the server side, what exception do you get? It's a bit crappy now and I always return 500 if the token isn't valid.

**Comment by spottedmahn** [comment]
Good question!  Not on the client side.  I just configured it for my tenant.

**Server Side Changes**

``` csharp
.AddJwtBearer(o =>
            {
                //o.Authority = Configuration["Jwt:Authority"];
                o.MetadataAddress = string.Format("https://login.microsoftonline.com/{0}/v2.0/.well-known/openid-configuration?p={1}", myTenant, myPolicy);
                //o.AuthenticationScheme = myPolicy;
                o.Audience = Configuration["Jwt:Audience"];
```
**Server Side Error**
>Authorization failed for user: (null)

**Comment by Gimly** [comment]
Well, I might be upon something, I saw that if I fix the redirect URI in the configuration, I can get the tokens without any issue as well. It might be that it's sending the full URI as redirect URI, and since B2C doesn't accept wildcards in redirect URIs, it's rejecting the more specific URI.

With the server, did you try setting the Authority instead of MetadataAddress? You can put it with the format.
```
https://login.microsoftonline.com/tfp/<tenant>.onmicrosoft.com/<policy>
```

**Comment by spottedmahn** [comment]
I got it working end-to-end!!  I stuck on how to get it back to GitHub.  I created a branch locally but now I can't push that branch.

>Error encountered while pushing branch to the remote repository: Git failed with a fatal error.
fatal: unable to access 'https://github.com/Gimly/NetCoreAngularAzureB2CMsal.git/': The requested URL returned error: 403
Pushing to https://github.com/Gimly/NetCoreAngularAzureB2CMsal.git

**Comment by spottedmahn** [comment]
Yes, I had to set the `MetaDataAddress`.  That resolved:

> IDX10501: Signature validation failed.  Unable to match 'kid'.

[Reference](https://stackoverflow.com/questions/43276977/azure-ad-b2c-error-idx10501-signature-validation-failed)

**Comment by spottedmahn** [comment]
>...Redirect uri...

Yes, that was my first issue.  I tried changing the port # to match but I still got:

> http://localhost:65328/redirect.html#error=redirect_uri_mismatch&error_description=AADB2C90006:+The+redirect+URI+'http://localhost:65328/'+provided+in+the+request+is+not+registered+for+the+client+id+'e760cab2-b9a1-4c0d-86fb-ff7084abd902'.
Correlation+ID:+56a1345b-edab-40b2-a999-3fc2a306400f
Timestamp:+2017-10-19+22:26:07Z
&state=b7526755-627a-47a5-89ca-0ad8a3cd5ca3

It would be nice to get this app working against the `fabrikam` demo tenant.

**Comment by Gimly** [comment]
Oh great news. You can't directly push changes to this repository, you need to create a fork to do this, that's how most open source projects work on GitHub. You need to click on the "Fork" button at the top-right corner of GitHub, then clone that repository. Do you changes there, preferably in a branch, and push the changes. Then, you go to GitHub again and click "New Pull Request", fill up, and send it. I will then receive the Pull request, be able to review it and merge the changes back. Check that documentation if you need more info: https://gist.github.com/Chaser324/ce0505fbed06b947d962

It definitely would be great to make it work on the Fabrikam demo tenant.

**Comment by spottedmahn** [comment]
Gotcha, thanks for info 😄, I'll fork it!  That was the plan actually.  Where I'm stuck is getting my changes from the current branch to the forked branch.

I've gotten in the habit of forking first then cloning but I forgot this time.

**Comment by Gimly** [comment]
Yeah, Git can get pretty confusing sometimes 😄. It's easy, just change the URL of the origin remote with your fork URL.
```
git remote set-url origin <your-fork-url>
```
I would also recommend that you put the original repo (mine) as an `upstream` remote, this way you can easily update your repo if I do changes.
```
git remote add upstream <my-repo-url>
```

**Comment by spottedmahn** [comment]
Nice!  I changed the origin url and [pushed it](https://github.com/spottedmahn/NetCoreAngularAzureB2CMsal/tree/dev/spottedmahn) but I can't create a [PR](https://github.com/Gimly/NetCoreAngularAzureB2CMsal/compare/master...spottedmahn:dev/spottedmahn?expand=1):

>Gimly:master and spottedmahn:dev/spottedmahn are entirely different commit histories.

I really appreciate ur help on this!

**Comment by Gimly** [comment]
Oh man, that's my fault, I did a force push this morning because I had done the commits with the wrong email address and I rewrote history to fix it 😖.

Sorry about that, the only way you can correct that is to clone to a clean folder and redon your changes there.

That's why you never rewrite history in git and force push are bad... But I didn't think someone had already cloned that repo. Sorry again.

**Comment by spottedmahn** [comment]
Ha, no worries.  Glad I know what the problem is.

**Comment by spottedmahn** [comment]
So I was just migrating my changes to the my fork and now I can't get an `access token`.  Like you said, the redirect uri is 'fully qualified' if you will.

![image](https://user-images.githubusercontent.com/14079228/31840674-67c40bc0-b5b4-11e7-9814-9bcef1fef9d9.png)

Once I added http://localhost:65328/home it started working again.

**Comment by Gimly** [comment]
Well, it's been confirmed by one of the developer of msal that the issue of the token not correctly being retrieved was linked to the library taking the current URL as redirect URI, which breaks the silent token retrieval process. This means that it's better anyway to set a fix redirect URI to the root of the application in the settings.

See:
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/150#issuecomment-338290672

**Comment by Gimly** [comment]
@spottedmahn OK, the code pushed to the repository is working 100% with the fabrikamb2c tenant, I'm very happy with that result!

I had to remove the `Development` flag because the `Environment` variable is not set yet when the `Startup` method is called unfortunately. I didn't find a good alternative so I just send the exception in any case. It's not very good, but it's OK until I find a better solution.

**Comment by spottedmahn** [comment]
@Gimly Nice!!

Please see this PR: https://github.com/Gimly/NetCoreAngularAzureB2CMsal/pull/8 for `IsDev` check.  I probably didn't sync my Fork in the proper way though; so I suspect you'll have some feedback for me on that!

**Comment by Gimly** [comment]
Merged PR. Yes, next time it's better to do a rebase instead of a merge commit. Basically, always do a `git fetch` instead of a `git pull` and then rebase your changes using `git rebase upstream/master` for example. This way you don't have a merge that complexifies the history. 

But that's fine, GitHub can fix that anyway by squashing pull requests 😄.

**Comment by spottedmahn** [comment]
I'll try that next time.  I like GUI's so I did it through the Web UI 😄 

I read through[ this SO post](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository) and found I could do it with a couple of quick clicks!
